export const policies: string[] = [
  "We collect basic account information such as your name, email address, and profile details when you register.",
  "We collect and process messages you send and receive to provide real-time communication services.",
  "We use your information to operate, maintain, and improve the functionality of our messaging platform.",
  "We may collect device and usage data to enhance performance and troubleshoot issues.",
  "We do not sell your personal information to third parties.",
  "We may share limited information with trusted service providers who help us operate our services.",
  "We implement security measures such as encryption to protect your data.",
  "We retain your data only for as long as necessary to provide our services or comply with legal obligations.",
  "You have the right to access, update, or delete your personal information at any time.",
  "We may use cookies or similar technologies to improve user experience.",
  "We may process your data to detect, prevent, and address fraud or security issues.",
  "We may disclose information if required to do so by law or valid legal requests.",
  "Your messages may be encrypted, but certain data may still be processed to deliver services.",
  "We allow you to control your privacy settings within the application.",
  "We do not knowingly collect personal data from children under the age of 13.",
  "We may update this privacy policy from time to time, and changes will be communicated through the app.",
  "We may store data on secure servers located in different regions.",
  "Third-party integrations may collect data in accordance with their own privacy policies.",
  "We take reasonable steps to protect your information but cannot guarantee absolute security.",
  "By using our service, you consent to the collection and use of your information as described in this policy.",
];
